/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApiV1RefuelingListRequest {
  pagination: ApiV0TypesPaginationParams;
  orderBy?: unknown;
  filter?: unknown;
}
/**
 * Params for an offset-based pagination.
 */
export interface ApiV0TypesPaginationParams {
  /**
   * list items startint at (but not including) the given item. Pass `null` to list from the beginning
   */
  from?: string | null;
  /**
   * How many results to fetch at most. Set to `null` to retrieve all items
   */
  limit?: number | null;
  [k: string]: unknown | undefined;
}
