/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApiV1RefuelingListResponse {
  refuelings: Refueling[];
}
export interface Refueling {
  id: number;
  litres: number;
  price: number;
  pricePerLitre: number;
  totalKilometers?: number;
  dayKilometers?: number;
  fullTank?: boolean;
  madeAt: string;
  userId?: string;
}
